/* Terroir — Lons-le-Saunier — auto-generated by publish-terroir.py */
window.PCV_DATA = (function () {
    const COLORS = { berth:'#c4a35a', market:'#d97706', shop:'#059669', mainland:'#7c3aed', logistics:'#2d4a5e', bougie:'#8a6a2e' };
    const CAT_LABELS = { berth:'Signature', market:'Market / Direct', shop:'Restaurant / Bar', mainland:'Out of town', logistics:'Logistics', bougie:'Prestige' };
    const PRODUCT_COLORS = {
    'Michelin':'#7f1d1d','Contemporary':'#1f2937','Traditional':'#a16207',
    'Cult':'#7c3aed','Cafe':'#92400e','Wine':'#7c2d12','Bacaro':'#7c3aed',
    'Drink':'#0ea5e9','Street Food':'#dc2626','Market':'#d97706',
    'Produce':'#15803d','Fish':'#3b82f6','Meat':'#b91c1c',
    'Cheese':'#eab308','Bread':'#a16207','Charcuterie':'#9d174d',
    'Hi-Fi':'#1f2937'
};
    const VENUES = [
  {
    "id": "v01-restaurant-jean-paul-jeunet",
    "cat": "shop",
    "tier": "berth_top",
    "priority": 1,
    "badge": "MICHELIN",
    "name": "Restaurant Jean-Paul Jeunet",
    "neighborhood": "Arbois — centre historique",
    "short": "Restaurant Jean-Paul Jeu",
    "lat": 46.9036,
    "lng": 5.7747,
    "tags": [
      "Michelin Guide — historic Arbois table, Vin Jaune as religion",
      "EUR 75-130 menu",
      "Essential",
      "Dinner"
    ],
    "productTags": [
      "Michelin"
    ],
    "why": "Michelin Guide — historic Arbois table, Vin Jaune as religion. What to order: Bresse poularde with Vin Jaune and morels; trout from the Doubs; Comté 36-month tart. The Vin Jaune sanctuary. Wine list of older Jaunes (Macle 1986, Tissot 1990) to look at and to drink. Book 10 days ahead in season.",
    "address": "9 rue de l'Hôtel de Ville, 39600 Arbois",
    "phone": "+33 3 84 66 05 67",
    "hours": "Dinner",
    "maps": "https://www.google.com/maps/search/?api=1&query=Restaurant+Jean-Paul+Jeunet+Lons-le-Saunier"
  },
  {
    "id": "v02-la-maison-carr-e-vincent-mercier",
    "cat": "shop",
    "tier": "berth_top",
    "priority": 2,
    "badge": "MICHELIN",
    "name": "La Maison Carrée — Vincent Mercier",
    "neighborhood": "Arbois — centre",
    "short": "La Maison Carrée — Vince",
    "lat": 46.902,
    "lng": 5.7726,
    "tags": [
      "Bib Gourmand — contemporary Jura bistronomy",
      "EUR 35-55 mains",
      "Recommended",
      "All day"
    ],
    "productTags": [
      "Michelin",
      "Contemporary"
    ],
    "why": "Bib Gourmand — contemporary Jura bistronomy. What to order: Montbéliarde beef tartare with Trousseau; pike-perch with smoked cancoillotte; waffle, fir-bud honey. Younger and freer than Jeunet. Tiny room, summer terrace. Vin Jaune by the glass, rare.",
    "address": "Rue de Faramand, 39600 Arbois",
    "phone": "",
    "hours": "All day",
    "maps": "https://www.google.com/maps/search/?api=1&query=La+Maison+Carrée+—+Vincent+Mercier+Lons-le-Saunier"
  },
  {
    "id": "v03-le-comtois",
    "cat": "shop",
    "tier": "berth_top",
    "priority": 3,
    "badge": "TRADITION",
    "name": "Le Comtois",
    "neighborhood": "Lons centre — quartier du marché",
    "short": "Le Comtois",
    "lat": 46.676,
    "lng": 5.555,
    "tags": [
      "Market bistro — Jura cooking without folklore",
      "EUR 18-28 plates",
      "Recommended",
      "Lunch"
    ],
    "productTags": [
      "Traditional"
    ],
    "why": "Market bistro — Jura cooking without folklore. What to order: Morteau sausage with green Jura lentils; coq au Vin Jaune; three-age Comté fondue. Packed on market days (Thursday, Saturday). Short slate menu, house-made cancoillotte. €22 lunch holds.",
    "address": "Rue de Pavigny, 39000 Lons-le-Saunier",
    "phone": "",
    "hours": "Lunch",
    "maps": "https://www.google.com/maps/search/?api=1&query=Le+Comtois+Lons-le-Saunier"
  },
  {
    "id": "v04-le-bistrot-des-halles",
    "cat": "shop",
    "tier": "several",
    "priority": 4,
    "badge": "TRADITION",
    "name": "Le Bistrot des Halles",
    "neighborhood": "Place de la Comédie / Halles",
    "short": "Le Bistrot des Halles",
    "lat": 46.6738,
    "lng": 5.553,
    "tags": [
      "Market address — regulars' clientele",
      "EUR 14-24 plates",
      "Walk-in",
      "Lunch"
    ],
    "productTags": [
      "Traditional"
    ],
    "why": "Halles regulars' canteen — lunch only, never the evening. What to order: Daily plat du jour; Comté tart; soup of the day. Lons centre, on Place de la Comédie facing the Halles. €15–22 plates, working-canteen energy.",
    "address": "Place de la Comédie, 39000 Lons-le-Saunier",
    "phone": "",
    "hours": "Lunch",
    "maps": "https://www.google.com/maps/search/?api=1&query=Le+Bistrot+des+Halles+Lons-le-Saunier"
  },
  {
    "id": "v05-h-tel-restaurant-le-parenth-se",
    "cat": "shop",
    "tier": "several",
    "priority": 5,
    "badge": "CONTEMPOR",
    "name": "Hôtel-Restaurant Le Parenthèse",
    "neighborhood": "Chille (5 min de Lons)",
    "short": "Hôtel-Restaurant Le Pare",
    "lat": 46.69,
    "lng": 5.57,
    "tags": [
      "Produce-driven cuisine — young team",
      "EUR 38-58 menu",
      "Recommended",
      "Dinner"
    ],
    "productTags": [
      "Contemporary"
    ],
    "why": "Country produce-driven restaurant — 5 min from Lons. What to order: Spring trout meunière; Maresme white asparagus; comté-and-walnut soufflé. Small dining room, weekly menu, the closest serious contemporary table to Lons.",
    "address": "Route de Besançon, 39570 Chille",
    "phone": "",
    "hours": "Dinner",
    "maps": "https://www.google.com/maps/search/?api=1&query=Hôtel-Restaurant+Le+Parenthèse+Lons-le-Saunier"
  },
  {
    "id": "v06-le-bouchon-du-stade",
    "cat": "shop",
    "tier": "several",
    "priority": 6,
    "badge": "TRADITION",
    "name": "Le Bouchon du Stade",
    "neighborhood": "Lons — quartier du Stade",
    "short": "Le Bouchon du Stade",
    "lat": 46.673,
    "lng": 5.547,
    "tags": [
      "Workers' canteen — country meats",
      "EUR 14-22 plates",
      "Walk-in",
      "Lunch"
    ],
    "productTags": [
      "Traditional"
    ],
    "why": "Workers' canteen near the stadium — country meats, Trousseau on the wall. What to order: Andouillette AAAAA; Morteau au Vin Jaune; Sunday daube. Beam ceilings, four-square tables, no ego. Half a dozen Trousseaux from named producers.",
    "address": "Avenue Camille Prost, 39000 Lons-le-Saunier",
    "phone": "",
    "hours": "Lunch",
    "maps": "https://www.google.com/maps/search/?api=1&query=Le+Bouchon+du+Stade+Lons-le-Saunier"
  },
  {
    "id": "v07-p-tisserie-chocolaterie-pelen",
    "cat": "shop",
    "tier": "several",
    "priority": 7,
    "badge": "CAFE",
    "name": "Pâtisserie Chocolaterie Pelen",
    "neighborhood": "Rue du Commerce (arcades)",
    "short": "Pâtisserie Chocolaterie ",
    "lat": 46.6748,
    "lng": 5.5544,
    "tags": [
      "Founded 1899 — galets de l'Ain (chocolate-praline pebbles)",
      "EUR 3-8",
      "Walk-in",
      "All day"
    ],
    "productTags": [
      "Cafe"
    ],
    "why": "Pâtisserie-chocolatier since 1899 — six generations of the Pelen family. What to order: Galet de l'Ain (chocolate-praline pebble, the house invention); Comté tart; coffee éclair. Tea room upstairs, marble tables, the bell rings when the door opens.",
    "address": "1 Rue du Commerce, 39000 Lons-le-Saunier",
    "phone": "+33 3 84 24 13 32",
    "hours": "All day",
    "maps": "https://www.google.com/maps/search/?api=1&query=Pâtisserie+Chocolaterie+Pelen+Lons-le-Saunier"
  },
  {
    "id": "v08-le-caf-de-la-com-die",
    "cat": "shop",
    "tier": "several",
    "priority": 8,
    "badge": "CAFE",
    "name": "Le Café de la Comédie",
    "neighborhood": "Place de la Comédie",
    "short": "Le Café de la Comédie",
    "lat": 46.6736,
    "lng": 5.5532,
    "tags": [
      "Café terrasse face au théâtre 1840",
      "EUR 2-12",
      "Walk-in",
      "All day"
    ],
    "productTags": [
      "Cafe"
    ],
    "why": "Café-bistrot on Place de la Comédie facing the Halles. What to order: Morning espresso and tartine; daily plat at lunch. The only Lons café terrace that reads the market in real time. Open 07:30, late.",
    "address": "Place de la Comédie, 39000 Lons-le-Saunier",
    "phone": "",
    "hours": "All day",
    "maps": "https://www.google.com/maps/search/?api=1&query=Le+Café+de+la+Comédie+Lons-le-Saunier"
  },
  {
    "id": "v09-caveau-des-jacobins",
    "cat": "shop",
    "tier": "several",
    "priority": 9,
    "badge": "DRINK",
    "name": "Caveau des Jacobins",
    "neighborhood": "Lons centre — Richebourg",
    "short": "Caveau des Jacobins",
    "lat": 46.6744,
    "lng": 5.5524,
    "tags": [
      "Cave à vins jurassiens — vente et dégustation",
      "EUR 6-15 verre",
      "Walk-in",
      "All day"
    ],
    "productTags": [
      "Wine"
    ],
    "why": "Lons caviste-and-bar — pours the seven Jura grape varieties by the glass. What to order: Three-Savagnin flight (ouillé / sous voile / Vin Jaune); glass of Trousseau next to Pinot Noir. The only Lons bar whose Jura list runs deep enough to compare three vintages of one cuvée.",
    "address": "12 Rue Richebourg, 39000 Lons-le-Saunier",
    "phone": "",
    "hours": "All day",
    "maps": "https://www.google.com/maps/search/?api=1&query=Caveau+des+Jacobins+Lons-le-Saunier"
  },
  {
    "id": "v10-march-de-lons-le-saunier",
    "cat": "market",
    "tier": "plenty",
    "priority": 10,
    "badge": "MARKET",
    "name": "Lons-le-Saunier Market",
    "neighborhood": "Place de la Comédie",
    "short": "Lons-le-Saunier Marke",
    "lat": 46.6738,
    "lng": 5.553,
    "tags": [
      "Thursday + Saturday morning market — one of the most beautiful in the Jura",
      "EUR variable",
      "Walk-in",
      "All day"
    ],
    "productTags": [
      "Market",
      "Produce",
      "Cheese"
    ],
    "why": "Lons market on Place de la Comédie (Thursday, Saturday). What to order: Marcel Petite Comté; smoked Morteau; fir-bud honey; plateau vegetables. The producer hour is 07:30–09:30; afterwards the stalls thin.",
    "address": "Place de la Comédie, 39000 Lons-le-Saunier",
    "phone": "",
    "hours": "All day",
    "maps": "https://www.google.com/maps/search/?api=1&query=Lons-le-Saunier+Market+Lons-le-Saunier"
  },
  {
    "id": "v11-fromagerie-vagne",
    "cat": "market",
    "tier": "plenty",
    "priority": 11,
    "badge": "PRODUCE",
    "name": "Fromagerie Vagne",
    "neighborhood": "Rue du Commerce (arcades)",
    "short": "Fromagerie Vagne",
    "lat": 46.675,
    "lng": 5.5546,
    "tags": [
      "Fromager-affineur du centre — Comté de plusieurs maisons",
      "EUR 5-25",
      "Walk-in",
      "All day"
    ],
    "productTags": [
      "Cheese",
      "Produce"
    ],
    "why": "Lons cheese reference, rue du Commerce — ages its own Comté. What to order: Three-age tasting plate (18 / 24 / 36 months); cancoillotte au Vin Jaune; raw-milk Morbier; Bleu de Gex. Vacuum-sealed wedges to take home — Comté travels.",
    "address": "Rue du Commerce, 39000 Lons-le-Saunier",
    "phone": "",
    "hours": "All day",
    "maps": "https://www.google.com/maps/search/?api=1&query=Fromagerie+Vagne+Lons-le-Saunier"
  },
  {
    "id": "v12-maison-du-comt",
    "cat": "shop",
    "tier": "plenty",
    "priority": 12,
    "badge": "CULT",
    "name": "Maison du Comté",
    "neighborhood": "Poligny (capitale du Comté)",
    "short": "Maison du Comté",
    "lat": 46.8389,
    "lng": 5.7064,
    "tags": [
      "Centre d'interprétation officiel du Comté AOP — visite cave",
      "EUR 8-12 visite",
      "Recommended",
      "All day"
    ],
    "productTags": [
      "Cheese"
    ],
    "why": "Maison du Comté in Poligny — the Comté PDO official site. What to order: Guided cellar visit; tasting flight; the maturation-and-fruitière story. The Comté PDO told in its own cellar; book the tour in advance.",
    "address": "Avenue de la Résistance, 39800 Poligny",
    "phone": "+33 3 84 37 78 40",
    "hours": "All day",
    "maps": "https://www.google.com/maps/search/?api=1&query=Maison+du+Comté+Lons-le-Saunier"
  },
  {
    "id": "v13-domaine-macle",
    "cat": "shop",
    "tier": "plenty",
    "priority": 13,
    "badge": "CULT",
    "name": "Domaine Macle",
    "neighborhood": "Château-Chalon (Vin Jaune)",
    "short": "Domaine Macle",
    "lat": 46.7556,
    "lng": 5.6394,
    "tags": [
      "Référence absolue du Vin Jaune de Château-Chalon",
      "EUR 25-95 bouteille",
      "Essential",
      "All day"
    ],
    "productTags": [
      "Wine"
    ],
    "why": "Reference Vin Jaune producer in Château-Chalon — 50 ha AOC enclave. What to order: Visit + cellar tasting; the new 2019 (just bottled March 2026) next to an older clavelin. Two days' notice for the appointment. The Vin Jaune cathedral.",
    "address": "Rue de la Roche, 39210 Château-Chalon",
    "phone": "+33 3 84 85 21 85",
    "hours": "All day",
    "maps": "https://www.google.com/maps/search/?api=1&query=Domaine+Macle+Lons-le-Saunier"
  },
  {
    "id": "v14-domaine-st-phane-tissot",
    "cat": "shop",
    "tier": "plenty",
    "priority": 14,
    "badge": "CULT",
    "name": "Domaine Stéphane Tissot",
    "neighborhood": "Montigny-lès-Arsures (Arbois)",
    "short": "Domaine Stéphane Tissot",
    "lat": 46.9244,
    "lng": 5.7853,
    "tags": [
      "Le Jura biodynamique — gamme la plus complète",
      "EUR 18-120 bouteille",
      "Recommended",
      "All day"
    ],
    "productTags": [
      "Wine"
    ],
    "why": "Stéphane Tissot — natural Jura reference, all seven grape varieties biodynamic. What to order: Cellar visit (Montigny-lès-Arsures); flight of Savagnin ouillé / sous voile / Vin Jaune; rare Trousseau and Poulsard cuvées. The most-respected natural-Jura name internationally.",
    "address": "39 Rue de Curon, 39600 Montigny-lès-Arsures",
    "phone": "+33 3 84 66 08 27",
    "hours": "All day",
    "maps": "https://www.google.com/maps/search/?api=1&query=Domaine+Stéphane+Tissot+Lons-le-Saunier"
  },
  {
    "id": "v15-maison-de-louis-pasteur",
    "cat": "shop",
    "tier": "plenty",
    "priority": 15,
    "badge": "CULT",
    "name": "Maison de Louis Pasteur",
    "neighborhood": "Arbois — centre historique",
    "short": "Maison de Louis Pasteur",
    "lat": 46.9039,
    "lng": 5.7758,
    "tags": [
      "Maison-laboratoire de Pasteur — préservée intacte",
      "EUR 7-9",
      "Recommended",
      "All day"
    ],
    "productTags": [
      "Cult"
    ],
    "why": "Family home and intact 1857 laboratory — only 19th-c. scientific lab preserved in original state in France. What to order: Guided tour of the lab + experimental vineyard. Where Pasteur understood alcoholic fermentation on Pupillin's Vin Jaune. Microbiology was born here. Apr–Nov, €7–9.",
    "address": "83 Rue de Courcelles, 39600 Arbois",
    "phone": "+33 3 84 66 11 72",
    "hours": "All day",
    "maps": "https://www.google.com/maps/search/?api=1&query=Maison+de+Louis+Pasteur+Lons-le-Saunier"
  },
  {
    "id": "v16-volaille-mi-ral-bresse",
    "cat": "market",
    "tier": "plenty",
    "priority": 16,
    "badge": "PRODUCE",
    "name": "Volaille Miéral (Bresse)",
    "neighborhood": "Bresse (Montrevel-en-Bresse)",
    "short": "Volaille Miéral (Bresse)",
    "lat": 46.3331,
    "lng": 5.1311,
    "tags": [
      "Volailler référent de la Bresse AOP — fournisseur de chefs",
      "EUR variable",
      "Recommended",
      "All day"
    ],
    "productTags": [
      "Meat"
    ],
    "why": "Bresse poultry producer — Volailles Miéral, AOP since 1957. What to order: Bresse poularde (the blue-footed PDO bird), guinea fowl, capon. The reference for Bresse poultry behind every Jura kitchen. Verify hours before driving.",
    "address": "Place de la Grenette, 01340 Montrevel-en-Bresse",
    "phone": "+33 4 74 25 48 36",
    "hours": "All day",
    "maps": "https://www.google.com/maps/search/?api=1&query=Volaille+Miéral+(Bresse)+Lons-le-Saunier"
  },
  {
    "id": "v17-salines-royales-d-arc-et-senans-unes",
    "cat": "shop",
    "tier": "plenty",
    "priority": 17,
    "badge": "CULT",
    "name": "Salines Royales d'Arc-et-Senans (UNESCO)",
    "neighborhood": "Arc-et-Senans (UNESCO)",
    "short": "Salines Royales d'Arc-et",
    "lat": 47.0331,
    "lng": 5.7767,
    "tags": [
      "UNESCO 1982 — saline royale Ledoux 1775, architecture utopique",
      "EUR 13-15",
      "Walk-in",
      "All day"
    ],
    "productTags": [
      "Cult"
    ],
    "why": "UNESCO 1982 — Ledoux 1775 utopian saline. What to order: Visit + summer Garden Festival (June–October). To understand the Jura salt chain: brine arrived here from Salins-les-Bains by wooden saumoduc to be evaporated. Ledoux's Enlightenment architecture, real fascination.",
    "address": "Grande Rue, 25610 Arc-et-Senans",
    "phone": "+33 3 81 54 45 45",
    "hours": "All day",
    "maps": "https://www.google.com/maps/search/?api=1&query=Salines+Royales+d'Arc-et-Senans+(UNESCO)+Lons-le-Saunier"
  },
  {
    "id": "p-bougie-germigney",
    "cat": "bougie",
    "tier": "plenty",
    "priority": 90,
    "badge": "PRESTIGE",
    "name": "Château de Germigney",
    "neighborhood": "Port-Lesney — 40 min north",
    "short": "Château de Germigney",
    "lat": 46.9783,
    "lng": 5.8128,
    "tags": ["18th-c. château directly on the Loue river — Relais & Châteaux for two decades, gastronomic restaurant", "EUR 120-200 dinner"],
    "productTags": [],
    "why": "An 18th-century château directly on the Loue river, French formal garden, Relais & Châteaux for two decades. Gastronomic restaurant: the slow luxury of the Jura. Seasonal programmes — truffle in winter, morels in May. Loue-facing terrace breakfast is the reason for the night.",
    "address": "Rue Edgar Faure, 39600 Port-Lesney",
    "phone": "",
    "hours": "Seasonal",
    "maps": "https://www.google.com/maps/search/?api=1&query=Château+de+Germigney+Port-Lesney"
  },
  {
    "id": "p-bougie-arlay",
    "cat": "bougie",
    "tier": "plenty",
    "priority": 91,
    "badge": "PRESTIGE",
    "name": "Château d'Arlay",
    "neighborhood": "Arlay — 10 km from Lons",
    "short": "Château d'Arlay",
    "lat": 46.7556,
    "lng": 5.5256,
    "tags": ["Family-owned 5 centuries — 18th-c. château + wine estate, Vin Jaune, Macvin, falconry", "EUR 10-25 visit + tasting"],
    "productTags": [],
    "why": "A private 18th-century château with a wine estate held by the same family (Laguiche) for five centuries — the longest unbroken family ownership in any Jura wine estate. Tours of gardens, château and cellars. Côtes du Jura wines, Vin Jaune, Macvin. Falconry still lives at the château. The Jura's quiet aristocracy.",
    "address": "Place de la Mairie, 39140 Arlay",
    "phone": "",
    "hours": "Apr–Oct",
    "maps": "https://www.google.com/maps/search/?api=1&query=Château+d+Arlay+Jura"
  },
  {
    "id": "p-bougie-monts-vaux",
    "cat": "bougie",
    "tier": "plenty",
    "priority": 92,
    "badge": "PRESTIGE",
    "name": "Hostellerie des Monts de Vaux",
    "neighborhood": "Poligny — 25 min from Lons",
    "short": "Monts de Vaux",
    "lat": 46.8424,
    "lng": 5.7126,
    "tags": ["Former post-house on the plateau — panoramic view over Poligny", "EUR 80-140 dinner"],
    "productTags": [],
    "why": "Former post-house on the plateau, panoramic view over Poligny and the Jura plain. Restaurant and hotel. Several successive reopenings — verify operating status before planning. When open, the kitchen runs the conservative Jura register.",
    "address": "Monts de Vaux, 39800 Poligny",
    "phone": "",
    "hours": "Verify",
    "maps": "https://www.google.com/maps/search/?api=1&query=Hostellerie+Monts+de+Vaux+Poligny"
  }
];
    const NEIGHBORHOODS = [
        { id: 'n-place-liberte', name: 'Place de la Liberté & rue du Commerce', center: [46.6748, 5.5544], radius: 180, maps_url: 'https://www.google.com/maps/search/?api=1&query=Place+de+la+Liberté+Lons-le-Saunier' },
        { id: 'n-place-comedie', name: 'Place de la Comédie / Halles', center: [46.6738, 5.5530], radius: 130, maps_url: 'https://www.google.com/maps/search/?api=1&query=Place+de+la+Comédie+Lons-le-Saunier' },
        { id: 'n-chevalerie', name: 'Quartier de la Chevalerie & Source Salée', center: [46.6722, 5.5480], radius: 280, maps_url: 'https://www.google.com/maps/search/?api=1&query=Parc+de+la+Chevalerie+Lons-le-Saunier' },
        { id: 'n-pavigny', name: 'Quartier du Stade / Pavigny', center: [46.6728, 5.5470], radius: 260, maps_url: 'https://www.google.com/maps/search/?api=1&query=Pavigny+Lons-le-Saunier' },
        { id: 'n-chille', name: 'Montciel & Chille', center: [46.6900, 5.5700], radius: 600, maps_url: 'https://www.google.com/maps/search/?api=1&query=Chille+Jura' },
        { id: 'n-arbois', name: 'Arbois (Jura wine capital)', center: [46.9036, 5.7747], radius: 700, maps_url: 'https://www.google.com/maps/search/?api=1&query=Arbois+Jura' },
        { id: 'n-chateau-chalon', name: 'Château-Chalon', center: [46.7556, 5.6394], radius: 350, maps_url: 'https://www.google.com/maps/search/?api=1&query=Château-Chalon' },
        { id: 'n-poligny', name: 'Poligny (Comté capital)', center: [46.8389, 5.7064], radius: 500, maps_url: 'https://www.google.com/maps/search/?api=1&query=Poligny+Jura' }
    ];
    const WALKS = [
        { id: 'w-arcades-aube', name: 'Rue du Commerce arcades at dawn', start: [46.6748, 5.5544], maps_url: 'https://www.google.com/maps/search/?api=1&query=Rue+du+Commerce+Lons-le-Saunier' },
        { id: 'w-chateau-chalon', name: 'Château-Chalon vineyard walk', start: [46.7556, 5.6394], maps_url: 'https://www.google.com/maps/search/?api=1&query=Château-Chalon+vignoble' },
        { id: 'w-arbois', name: 'Arbois old town', start: [46.9036, 5.7747], maps_url: 'https://www.google.com/maps/search/?api=1&query=Arbois+centre+ville' },
        { id: 'w-baume', name: 'Baume-les-Messieurs cirque', start: [46.7095, 5.6450], maps_url: 'https://www.google.com/maps/search/?api=1&query=Baume-les-Messieurs' },
        { id: 'w-cirque-fer-cheval', name: 'Cirque du Fer-à-Cheval', start: [46.6900, 5.6800], maps_url: 'https://www.google.com/maps/search/?api=1&query=Cirque+du+Fer+à+Cheval+Jura' },
        { id: 'w-source-salee', name: 'Source Salée pool', start: [46.6722, 5.5485], maps_url: 'https://www.google.com/maps/search/?api=1&query=Source+Salée+Lons-le-Saunier' }
    ];
    const LANDMARKS = [
        { id: 'l-eglise-saint-just', name: 'Église Saint-Just (Arbois)', coords: [46.9020, 5.7745], maps_url: 'https://www.google.com/maps/search/?api=1&query=Église+Saint-Just+Arbois' },
        { id: 'l-pasteur-arbois', name: 'Maison de Pasteur (Arbois)', coords: [46.9036, 5.7747], maps_url: 'https://www.google.com/maps/search/?api=1&query=Maison+de+Pasteur+Arbois' },
        { id: 'l-bartholdi', name: 'Statue Rouget de Lisle (Bartholdi, 1882)', coords: [46.6748, 5.5544], maps_url: 'https://www.google.com/maps/search/?api=1&query=Statue+Rouget+de+Lisle+Bartholdi+Lons-le-Saunier' }
    ];
    const WORK_SPOTS = [
        { id: 'p-work-mediatheque', name: 'Médiathèque', start: [46.6740, 5.5520] },
        { id: 'p-work-parc-chevalerie', name: 'Parc de la Chevalerie', start: [46.6722, 5.5480] },
        { id: 'p-work-cafe-comedie', name: 'Café de la Comédie', start: [46.6736, 5.5532] },
        { id: 'p-work-rue-arcades', name: 'Rue du Commerce arcades', start: [46.6748, 5.5544] },
        { id: 'p-work-bibliotheque-arbois', name: 'Bibliothèque d’Arbois', start: [46.9036, 5.7747] }
    ];
    return { VENUES, COLORS, CAT_LABELS, PRODUCT_COLORS, NEIGHBORHOODS, WALKS, WORK_SPOTS, LANDMARKS };
})();
