/* Terroir — Barcelona — auto-generated, hand-tuned for resident-grade depth */
window.PCV_DATA = (function () {
    const COLORS = { berth:'#c4a35a', market:'#d97706', shop:'#059669', mainland:'#7c3aed', logistics:'#2d4a5e', bougie:'#8a6a2e' };
    const CAT_LABELS = { berth:'Signature', market:'Market / Direct', shop:'Restaurant / Bar', mainland:'Out of town', logistics:'Logistics', bougie:'Prestige' };
    const PRODUCT_COLORS = {
    'Michelin':'#7f1d1d','Contemporary':'#1f2937','Traditional':'#a16207',
    'Cult':'#7c3aed','Cafe':'#92400e','Wine':'#7c2d12','Bacaro':'#7c3aed',
    'Drink':'#0ea5e9','Street Food':'#dc2626','Market':'#d97706',
    'Produce':'#15803d','Fish':'#3b82f6','Meat':'#b91c1c',
    'Cheese':'#eab308','Bread':'#a16207','Charcuterie':'#9d174d',
    'Hi-Fi':'#1f2937','Vermut':'#a16207','NaturalWine':'#7c2d12'
};
    const VENUES = [
  { "id": "v01-disfrutar", "cat": "shop", "tier": "berth_top", "priority": 1, "badge": "MICHELIN", "name": "Disfrutar", "neighborhood": "Eixample · Carrer Villarroel 163", "lat": 41.3942, "lng": 2.1602, "tags": ["3★ Michelin since 2024 · World's #1 Restaurant 2024 · El Bulli alumni", "EUR 280-380 tasting", "Essential", "Dinner"], "productTags": ["Michelin"], "why": "World's #1 Restaurant 2024. Castro/Xatruch/Casañas, three Roca-and-El-Bulli alumni. Tasting menu only — playful, technically rigorous, the closest living echo to El Bulli. Book 3-4 months ahead.", "address": "Carrer de Villarroel 163, 08036", "phone": "", "hours": "Tue-Sat dinner", "maps": "https://www.google.com/maps/search/?api=1&query=Disfrutar+Barcelona" },
  { "id": "v02-abac", "cat": "shop", "tier": "berth_top", "priority": 2, "badge": "MICHELIN", "name": "ABaC", "neighborhood": "Sant Gervasi · Av. del Tibidabo 1", "lat": 41.4079, "lng": 2.1335, "tags": ["3★ Michelin · Jordi Cruz", "EUR 245-310 tasting", "Essential", "Dinner"], "productTags": ["Michelin"], "why": "Jordi Cruz — the youngest Michelin-3★ chef in Spanish history. Modern Catalan technique, hotel-restaurant inside ABaC Restaurant Hotel. Long cellar, formal service, the upper register.", "address": "Av. del Tibidabo 1, 08022", "phone": "", "hours": "Tue-Sat", "maps": "https://www.google.com/maps/search/?api=1&query=ABaC+Restaurant+Barcelona" },
  { "id": "v03-lasarte", "cat": "shop", "tier": "berth_top", "priority": 3, "badge": "MICHELIN", "name": "Lasarte", "neighborhood": "Eixample · Hotel Monument", "lat": 41.3942, "lng": 2.1656, "tags": ["3★ Michelin · Berasategui's BCN flagship", "EUR 240-310 tasting"], "productTags": ["Michelin"], "why": "Martín Berasategui's Barcelona flagship — Basque rigor inside an Eixample palace hotel. Paolo Casagrande heads the kitchen day-to-day. The most operationally polished 3★ in town.", "address": "Carrer de Mallorca 259, 08008", "phone": "", "hours": "Tue-Sat", "maps": "https://www.google.com/maps/search/?api=1&query=Lasarte+Restaurant+Barcelona" },
  { "id": "v04-hermanos-torres", "cat": "shop", "tier": "berth_top", "priority": 4, "badge": "MICHELIN", "name": "Cocina Hermanos Torres", "neighborhood": "Les Corts · Taquígraf Serra 20", "lat": 41.3892, "lng": 2.1271, "tags": ["3★ Michelin · Sergio + Javier Torres twin chefs", "EUR 200-260 tasting"], "productTags": ["Michelin"], "why": "Sergio and Javier Torres (twins) cook in the round at a kitchen-as-stage. Open dining room around the kitchen, modern Mediterranean, ingredient-forward. The most theatrical of the BCN 3★s.", "address": "Carrer del Taquígraf Serra 20, 08029", "phone": "", "hours": "Tue-Sat", "maps": "https://www.google.com/maps/search/?api=1&query=Cocina+Hermanos+Torres+Barcelona" },
  { "id": "v05-moments", "cat": "shop", "tier": "berth_top", "priority": 5, "badge": "MICHELIN", "name": "Moments", "neighborhood": "Eixample · Mandarin Oriental, Passeig de Gràcia", "lat": 41.3956, "lng": 2.1631, "tags": ["2★ Michelin · Carme Ruscalleda", "EUR 200-260 tasting"], "productTags": ["Michelin"], "why": "Carme Ruscalleda — the only Spanish female chef ever to hold 7★ across multiple restaurants — runs Moments inside Mandarin Oriental with her son Raül Balam. Catalan tradition refined to fine-dining grammar. Book early.", "address": "Passeig de Gràcia 38-40, 08007", "phone": "", "hours": "Tue-Sat", "maps": "https://www.google.com/maps/search/?api=1&query=Moments+Mandarin+Oriental+Barcelona" },
  { "id": "v06-canete", "cat": "berth", "tier": "berth_top", "priority": 6, "badge": "TRADITION", "name": "Bar Cañete", "neighborhood": "Raval · Carrer Unió 17", "lat": 41.3793, "lng": 2.1740, "tags": ["Counter dining, grilled vegetables, classic Spanish", "EUR 30-55 mains", "Essential", "Lunch + dinner"], "productTags": ["Traditional"], "why": "The Catalan classic-counter benchmark — long zinc bar, vegetables grilled à la plancha, navajas, anchoas, the Galician-Catalan classics done correctly. Sit at the counter and watch the show. Book lunch.", "address": "Carrer de la Unió 17, 08001", "phone": "", "hours": "13:00-16:00, 20:00-23:30", "maps": "https://www.google.com/maps/search/?api=1&query=Bar+Canete+Barcelona" },
  { "id": "v07-cal-pep", "cat": "berth", "tier": "berth_top", "priority": 7, "badge": "TRADITION", "name": "Cal Pep", "neighborhood": "Born · Plaça de les Olles 8", "lat": 41.3839, "lng": 2.1830, "tags": ["Counter-tapas legend, no menu, what Pep cooks today", "EUR 25-50 plates", "Essential", "Lunch + dinner"], "productTags": ["Traditional"], "why": "An institution — counter only, ask Pep what's on, get fed. Tortillita de camarones, scrambled eggs with chistorra and morcilla, fresh anchovies. Closed Sun + Mon. Arrive 12:45 or 19:30.", "address": "Plaça de les Olles 8, 08003", "phone": "", "hours": "Tue-Sat", "maps": "https://www.google.com/maps/search/?api=1&query=Cal+Pep+Barcelona" },
  { "id": "v08-quimet", "cat": "berth", "tier": "berth_top", "priority": 8, "badge": "INSTITUTION", "name": "Quimet i Quimet", "neighborhood": "Poble Sec · Poeta Cabanyes 25", "lat": 41.3729, "lng": 2.1611, "tags": ["1914 conserva-and-cava counter — montaditos, 5 generations", "EUR 12-25 montaditos", "Essential", "Lunch + early evening"], "productTags": ["Vermut"], "why": "Five generations of the same family since 1914. Six-square-metre standing-room only. Walls are floor-to-ceiling preserved-fish tins. The signature montaditos: anchovy + foie gras, salmon + yogurt + truffle honey. Open lunch + 19:00-22:00. Closed Sun.", "address": "Carrer del Poeta Cabanyes 25, 08004", "phone": "", "hours": "12:00-16:00, 19:00-22:30 (closed Sun)", "maps": "https://www.google.com/maps/search/?api=1&query=Quimet+i+Quimet+Barcelona" },
  { "id": "v09-cova-fumada", "cat": "berth", "tier": "berth_top", "priority": 9, "badge": "INSTITUTION", "name": "La Cova Fumada", "neighborhood": "Barceloneta · Carrer del Baluard 56", "lat": 41.3787, "lng": 2.1909, "tags": ["1944 fishermen's tasca · invented the bomba potato", "EUR 8-16 plates", "Essential", "Lunch only"], "productTags": ["Traditional"], "why": "The bomba was invented here in 1944. A working-class barceloneta tasca with no sign on the door — chalk menu on butcher's paper. Bomba (deep-fried potato bomb stuffed with meat ragù), cap-i-pota (head and trotters), squid à la plancha. Lunch only. Cash only. Closed Sun.", "address": "Carrer del Baluard 56, 08003", "phone": "", "hours": "Tue-Sat 09:00-16:00", "maps": "https://www.google.com/maps/search/?api=1&query=La+Cova+Fumada+Barceloneta" },
  { "id": "v10-can-mano", "cat": "berth", "tier": "berth_top", "priority": 10, "badge": "INSTITUTION", "name": "Can Maño", "neighborhood": "Barceloneta · Carrer del Baluard 12", "lat": 41.3805, "lng": 2.1887, "tags": ["What fishermen ate · grilled fish + vino de la casa in a porrón", "EUR 8-18 plates", "Recommended", "Lunch + dinner"], "productTags": ["Traditional"], "why": "A barceloneta tasca where house wine arrives in a porrón (the Catalan glass spout-pitcher) and the fish is whatever the Boqueria sold them at 11. Grilled sardines, calamares à la plancha, sepia. Cash only. Closed Sun.", "address": "Carrer del Baluard 12, 08003", "phone": "", "hours": "Tue-Sat", "maps": "https://www.google.com/maps/search/?api=1&query=Can+Mano+Barceloneta" },
  { "id": "v11-bar-tomas", "cat": "berth", "tier": "berth_top", "priority": 11, "badge": "INSTITUTION", "name": "Bar Tomás", "neighborhood": "Sarrià · Carrer Major de Sarrià 49", "lat": 41.4040, "lng": 2.1273, "tags": ["1949 · the patatas bravas reference of Barcelona", "EUR 4-12 plates", "Essential", "Lunch + early evening"], "productTags": ["Traditional"], "why": "Open since 1949, the patatas bravas reference of Barcelona — slightly burnt edges, two sauces (red brava + ali-oli) served separately, double-fry method. The neighborhood-Sarrià version of a national obsession. Closed Tue + Wed.", "address": "Carrer Major de Sarrià 49, 08017", "phone": "", "hours": "Thu-Mon 12:00-15:30, 18:00-22:00", "maps": "https://www.google.com/maps/search/?api=1&query=Bar+Tomas+Sarria" },
  { "id": "v12-marsella", "cat": "shop", "tier": "berth_top", "priority": 12, "badge": "STORY", "name": "Bar Marsella", "neighborhood": "Raval · Carrer Sant Pau 65", "lat": 41.3789, "lng": 2.1690, "tags": ["1820 · the absinthe bar where Picasso, Hemingway, Gaudí drank", "EUR 5-9 absinthe ritual", "Essential", "Evening"], "productTags": ["Cult"], "why": "Open since 1820 — the oldest bar in Barcelona. Picasso, Hemingway, Gaudí, Dalí all drank here. Absinthe served the ritual way: sugar cube on a slotted spoon, ice water dripped through. The dust on the bottles is real. Open evening only.", "address": "Carrer de Sant Pau 65, 08001", "phone": "", "hours": "Daily 22:00-02:00", "maps": "https://www.google.com/maps/search/?api=1&query=Bar+Marsella+Barcelona" },
  { "id": "v13-pastis", "cat": "shop", "tier": "berth_top", "priority": 13, "badge": "STORY", "name": "Bar Pastís", "neighborhood": "Raval · Carrer Santa Mònica 4", "lat": 41.3788, "lng": 2.1742, "tags": ["1947 · tiny Edith Piaf bar piping French chanson on vinyl", "EUR 4-8 drinks", "Recommended", "Evening"], "productTags": ["Cult"], "why": "Tiny 1947 Raval bar — Edith Piaf and Jacques Brel still pipe through the vinyl, walls covered in old French posters, the bartender pours pastis or anís with the same gesture for 50 years. 12 standing places. Late only.", "address": "Carrer de Santa Mònica 4, 08001", "phone": "", "hours": "Daily 19:30-02:00", "maps": "https://www.google.com/maps/search/?api=1&query=Bar+Pastis+Barcelona" },
  { "id": "v14-granja-viader", "cat": "berth", "tier": "berth_top", "priority": 14, "badge": "INSTITUTION", "name": "Granja Viader", "neighborhood": "Raval · Carrer Xuclà 4", "lat": 41.3823, "lng": 2.1714, "tags": ["1870 granja · invented Cacaolat (Spain's chocolate-milk classic)", "EUR 3-7 chocolate + suís", "Essential", "Morning + tarda"], "productTags": ["Cafe"], "why": "Open since 1870. The Viader family invented Cacaolat (Spain's chocolate-milk benchmark) here in 1931. Hot chocolate so thick a churro stands in it; suís (chocolate + whipped cream) is the slow-afternoon order. Closed Sun + Mon. Marble tables, ham hanging from the ceiling.", "address": "Carrer d'en Xuclà 4-6, 08001", "phone": "", "hours": "Tue-Sat 09:00-13:30, 17:00-21:00", "maps": "https://www.google.com/maps/search/?api=1&query=Granja+Viader+Barcelona" },
  { "id": "v15-quatre-gats", "cat": "shop", "tier": "berth_top", "priority": 15, "badge": "STORY", "name": "Els 4 Gats", "neighborhood": "Gothic · Carrer Montsió 3 bis", "lat": 41.3842, "lng": 2.1738, "tags": ["1897 Modernist café · Picasso's first solo show 1900", "EUR 25-45 mains", "Recommended", "Lunch + dinner"], "productTags": ["Cult"], "why": "Modernist café-tavern open since 1897 (in a Puig i Cadafalch building). Pere Romeu's salon was the haunt of Picasso, Casas, Rusiñol, Domènech. Picasso's first solo show happened here in 1900 — and he drew the menu. The food is honest Catalan, but the room is what you book.", "address": "Carrer de Montsió 3 bis, 08002", "phone": "", "hours": "Tue-Sun 10:00-00:00", "maps": "https://www.google.com/maps/search/?api=1&query=Els+Quatre+Gats+Barcelona" },
  { "id": "v16-casa-almirall", "cat": "shop", "tier": "berth_top", "priority": 16, "badge": "STORY", "name": "Casa Almirall", "neighborhood": "Raval · Carrer Joaquín Costa 33", "lat": 41.3819, "lng": 2.1657, "tags": ["1860 · Barcelona's oldest bar, Modernist interior intact", "EUR 4-9 drinks", "Recommended", "Evening"], "productTags": ["Cult"], "why": "Open since 1860 — Barcelona's oldest bar, full Modernist interior preserved (mirrors, wood, 1888 Universal Expo Muse). Vermut at noon, absinthe ritual late, no nostalgia tax. Closed Sun.", "address": "Carrer de Joaquín Costa 33, 08001", "phone": "", "hours": "Tue-Sat 19:00-02:30", "maps": "https://www.google.com/maps/search/?api=1&query=Casa+Almirall+Barcelona" },
  { "id": "v17-boadas", "cat": "shop", "tier": "berth_top", "priority": 17, "badge": "COCKTAIL", "name": "Boadas", "neighborhood": "Eixample · Carrer Tallers 1", "lat": 41.3815, "lng": 2.1696, "tags": ["1933 · oldest cocktail bar in BCN, Hemingway drank here", "EUR 9-14 cocktails", "Essential", "Evening"], "productTags": ["Cult"], "why": "Open since 1933 — Barcelona's oldest cocktail bar, founded by Miguel Boadas (apprentice at La Floridita Havana, where the daiquiri was invented). Stand at the bar in jacket-and-tie reverence, order Boadas' own cocktail. Hemingway drank here.", "address": "Carrer dels Tallers 1, 08001", "phone": "", "hours": "Mon-Sat 12:00-02:00", "maps": "https://www.google.com/maps/search/?api=1&query=Boadas+Cocktail+Bar+Barcelona" },
  { "id": "v18-dry-martini", "cat": "shop", "tier": "berth_top", "priority": 18, "badge": "COCKTAIL", "name": "Dry Martini", "neighborhood": "Eixample · Carrer Aribau 162", "lat": 41.3923, "lng": 2.1568, "tags": ["1978 · Javier de las Muelas, the dry-martini temple", "EUR 13-17 cocktails", "Essential", "Evening + late"], "productTags": ["Cult"], "why": "Open since 1978 — Javier de las Muelas' dry-martini temple. The Speakeasy hidden in the kitchen behind the bar is the actual restaurant; the front is the cocktail counter. Their dry martini is the city's reference.", "address": "Carrer d'Aribau 162-166, 08036", "phone": "", "hours": "Daily 13:00-02:30", "maps": "https://www.google.com/maps/search/?api=1&query=Dry+Martini+Bar+Barcelona" },
  { "id": "v19-paradiso", "cat": "shop", "tier": "berth_top", "priority": 19, "badge": "COCKTAIL", "name": "Paradiso", "neighborhood": "Born · Carrer Rera Palau 4", "lat": 41.3849, "lng": 2.1844, "tags": ["Speakeasy through a pastrami sandwich · World's #1 Bar 2022", "EUR 14-18 cocktails", "Essential", "Evening + late"], "productTags": ["Cult"], "why": "Walk into the pastrami-sandwich shop; the wall opens. Inside: Giacomo Giannotti's vault-like speakeasy, smoke-and-mirrors cocktails, World's Best Bar 2022. The most theatrical drink in BCN — and surprisingly serious about flavor.", "address": "Carrer de Rera Palau 4, 08003", "phone": "", "hours": "Daily 19:00-02:30", "maps": "https://www.google.com/maps/search/?api=1&query=Paradiso+Barcelona" },
  { "id": "v20-sips", "cat": "shop", "tier": "berth_top", "priority": 20, "badge": "COCKTAIL", "name": "Sips", "neighborhood": "Eixample · Carrer Muntaner 108", "lat": 41.3967, "lng": 2.1556, "tags": ["World's #1 Bar 2023 · Simone Caporale + Marc Álvarez", "EUR 14-18 cocktails"], "productTags": ["Cult"], "why": "World's #1 Bar 2023. Simone Caporale (ex-Artesian London) and Marc Álvarez (ex-Tickets) — half-cocktail-bar half-laboratory. Curved oak counter, no menu, the bartender drives. Reserve.", "address": "Carrer de Muntaner 108, 08036", "phone": "", "hours": "Tue-Sat 18:00-02:00", "maps": "https://www.google.com/maps/search/?api=1&query=Sips+Bar+Barcelona" },
  { "id": "v21-two-schmucks", "cat": "shop", "tier": "berth_top", "priority": 21, "badge": "COCKTAIL", "name": "Two Schmucks", "neighborhood": "Raval · Carrer Joaquín Costa 52", "lat": 41.3814, "lng": 2.1665, "tags": ["Top-50 World's Best Bars · irreverent, no rules", "EUR 9-13 cocktails"], "productTags": ["Cult"], "why": "Top 50 in the world. Irreverent, music loud, no dress code, sometimes a llama at the door. The drinks are seriously made; the room is intentionally not. Sister bar to Sips' formal mood.", "address": "Carrer de Joaquín Costa 52, 08001", "phone": "", "hours": "Daily 18:00-02:30", "maps": "https://www.google.com/maps/search/?api=1&query=Two+Schmucks+Barcelona" },
  { "id": "v22-plastic-bar", "cat": "shop", "tier": "berth_top", "priority": 22, "badge": "HI-FI", "name": "Plàstic Bar", "neighborhood": "Sant Pere · listening bar / vinyl", "lat": 41.3866, "lng": 2.1771, "tags": ["BCN reference for vinyl + serious sound", "EUR 6-12 drinks"], "productTags": ["Hi-Fi"], "why": "The Barcelona reference for vinyl-and-serious-sound. Tube amp-and-vintage-speaker setup, deep wall of records (jazz, dub, Catalan psych, Balearic), conversation lowered as the music plays. The closest BCN gets to a Tokyo jazz-kissa.", "address": "Sant Pere — verify exact address before going", "phone": "", "hours": "Evening", "maps": "https://www.google.com/maps/search/?api=1&query=Plastic+Bar+Barcelona+vinyl" },
  { "id": "v23-bar-brutal", "cat": "shop", "tier": "berth_top", "priority": 23, "badge": "NATURAL WINE", "name": "Bar Brutal", "neighborhood": "Born · Carrer Princesa 14", "lat": 41.3848, "lng": 2.1818, "tags": ["The Catalan natural-wine reference · 5,000-bottle cellar", "EUR 5-12 glass · EUR 30-90 bottle", "Essential", "Evening"], "productTags": ["NaturalWine"], "why": "Sister of Can Cisa. The natural-wine reference of Catalonia — 5,000+ bottles, the deepest cellar of small-grower Catalan, French and Italian natural wines anywhere in the city. Small plates: anchovy, terrines, sausages. The room fills by 21:00.", "address": "Carrer de la Princesa 14, 08003", "phone": "", "hours": "Tue-Sat 13:00-15:30, 19:00-00:30", "maps": "https://www.google.com/maps/search/?api=1&query=Bar+Brutal+Barcelona" },
  { "id": "v24-bormuth", "cat": "berth", "tier": "berth_top", "priority": 24, "badge": "VERMUT", "name": "Bormuth", "neighborhood": "Born · Carrer Rec 31", "lat": 41.3848, "lng": 2.1819, "tags": ["Vermut + classic tapas, the Born reference", "EUR 4-12 plates", "Recommended", "Lunch + evening"], "productTags": ["Vermut"], "why": "The Born reference for vermut + serious classic tapas: bombas, croquetes, esqueixada, anxoves del Cantàbric. Open all day, the right Sunday l'hora del vermut stop. Walk-in early, busy after 13:30.", "address": "Carrer del Rec 31, 08003", "phone": "", "hours": "Daily 12:00-01:00", "maps": "https://www.google.com/maps/search/?api=1&query=Bormuth+Barcelona" },
  { "id": "v25-xampanyet", "cat": "berth", "tier": "berth_top", "priority": 25, "badge": "INSTITUTION", "name": "El Xampanyet", "neighborhood": "Born · Carrer Montcada 22", "lat": 41.3855, "lng": 2.1817, "tags": ["1929 cava-and-anchovy bar, ten generations of Esteva family", "EUR 3-8 plates"], "productTags": ["Vermut"], "why": "Open since 1929 — three generations of the Esteva family. Tile walls, ham hooks, house cava in tiny glasses, anchovies-with-vinegar from Cantàbria, jamón. The Born ritual address. No reservations, arrive 12:30 or 19:30.", "address": "Carrer de Montcada 22, 08003", "phone": "", "hours": "Tue-Sat 12:00-15:30, 19:00-23:00", "maps": "https://www.google.com/maps/search/?api=1&query=El+Xampanyet+Barcelona" },
  { "id": "v26-pinotxo", "cat": "berth", "tier": "berth_top", "priority": 26, "badge": "INSTITUTION", "name": "Bar Pinotxo (Boqueria)", "neighborhood": "Boqueria · stall 466", "lat": 41.3819, "lng": 2.1718, "tags": ["1940 · Juanito's grandson Marc cooks the daily-catch counter", "EUR 5-15 plates"], "productTags": ["Vermut"], "why": "Inside Boqueria since 1940 — three generations behind the same 12-stool counter. Whatever the morning's market sold them: garbanzos with morcilla, scrambled eggs with chistorra, bacalla amb mel. Closed Sun + Mon. Arrive 09:30 or 13:00.", "address": "Mercat de la Boqueria, stall 466-470", "phone": "", "hours": "Tue-Sat 06:30-15:30", "maps": "https://www.google.com/maps/search/?api=1&query=Bar+Pinotxo+Boqueria" },
  { "id": "v27-suculent", "cat": "berth", "tier": "berth_top", "priority": 27, "badge": "MICHELIN PLATE", "name": "Suculent", "neighborhood": "Raval · Rambla del Raval 43", "lat": 41.3795, "lng": 2.1716, "tags": ["Carles Abellán's wood-fire kitchen · Michelin Plate", "EUR 25-50 mains"], "productTags": ["Contemporary"], "why": "Carles Abellán (former El Bulli, before Tapas 24). Wood-fired pigeon, suckling lamb, wood-charred vegetables. Michelin Plate. Modern Catalan that pulls hard at terroir without losing technique.", "address": "Rambla del Raval 43, 08001", "phone": "", "hours": "Tue-Sun", "maps": "https://www.google.com/maps/search/?api=1&query=Suculent+Restaurant+Barcelona" },
  { "id": "v28-direkte-boqueria", "cat": "berth", "tier": "berth_top", "priority": 28, "badge": "MICHELIN", "name": "Direkte Boqueria", "neighborhood": "Boqueria · stall 218-219", "lat": 41.3819, "lng": 2.1718, "tags": ["1★ Michelin · 8-seat counter inside Boqueria, Asian-Catalan", "EUR 90-130 tasting"], "productTags": ["Michelin"], "why": "8 seats. A Michelin-starred counter inside the Boqueria — Arnau Muñío cooks Asian-Catalan from the market produce three metres away. The most physical-place-meets-refined-cooking address in the city. Book months ahead.", "address": "Mercat de la Boqueria, stalls 218-219", "phone": "", "hours": "Tue-Sat", "maps": "https://www.google.com/maps/search/?api=1&query=Direkte+Boqueria" },
  { "id": "v29-aleia", "cat": "berth", "tier": "berth_top", "priority": 29, "badge": "MICHELIN", "name": "Aleia", "neighborhood": "Gràcia · Hotel Casa Fuster, Passeig de Gràcia 132", "lat": 41.3989, "lng": 2.1572, "tags": ["1★ Michelin · Paulo Airaudo, modern Italian-Catalan crossover", "EUR 165-205 tasting"], "productTags": ["Michelin"], "why": "Paulo Airaudo (Hong Kong + La Bottega Argentina) inside the Domènech i Montaner Modernist Hotel Casa Fuster. Italian-Catalan crossover, polished service, the Modernist room is the bonus.", "address": "Passeig de Gràcia 132, 08008", "phone": "", "hours": "Tue-Sat", "maps": "https://www.google.com/maps/search/?api=1&query=Aleia+Restaurant+Barcelona" },
  { "id": "v30-cinc-sentits", "cat": "berth", "tier": "berth_top", "priority": 30, "badge": "MICHELIN", "name": "Cinc Sentits", "neighborhood": "Eixample · Carrer Aribau 58", "lat": 41.3911, "lng": 2.1601, "tags": ["1★ Michelin · Jordi Artal, modern Catalan with Canadian-Catalan story", "EUR 140-180 tasting"], "productTags": ["Michelin"], "why": "Jordi Artal — born in Canada to Catalan parents, returned and built one of Eixample's most accessible Michelin tables. Modern Catalan rooted in family memory: pa amb tomàquet course, Maresme peas, Costa Brava sea bass. Lunch tasting is the value move.", "address": "Carrer d'Aribau 58, 08011", "phone": "", "hours": "Tue-Sat", "maps": "https://www.google.com/maps/search/?api=1&query=Cinc+Sentits+Barcelona" },
  { "id": "v31-vinya-senyor", "cat": "berth", "tier": "berth_top", "priority": 31, "badge": "WINE BAR", "name": "La Vinya del Senyor", "neighborhood": "Born · Plaça Santa Maria 5", "lat": 41.3838, "lng": 2.1828, "tags": ["Tiny wine bar facing Santa Maria del Mar · curated short list", "EUR 4-10 glass"], "productTags": ["Wine"], "why": "A wine bar so small it's mostly the terrace facing Santa Maria del Mar (the most beautiful Catalan-Gothic basilica). The list rotates weekly — Catalan, Iberian and small-grower French. Arrive 18:30 to claim a terrace table for sunset.", "address": "Plaça de Santa Maria 5, 08003", "phone": "", "hours": "Daily 12:00-01:00", "maps": "https://www.google.com/maps/search/?api=1&query=La+Vinya+del+Senyor+Barcelona" },
  { "id": "v32-bar-mut", "cat": "berth", "tier": "berth_top", "priority": 32, "badge": "MODERN", "name": "Bar Mut", "neighborhood": "Eixample · Carrer Pau Claris 192", "lat": 41.3950, "lng": 2.1622, "tags": ["Modern Catalan tapas counter · long for late-evening sit-down", "EUR 12-30 plates"], "productTags": ["Contemporary"], "why": "An Eixample standing-bar that became a sit-down room. Modern Catalan tapas — esqueixada, txuleta, hand-cut jamón, fresh anchovies. Counter dinner here is the cleanest Eixample-after-9pm move when Boadas is full.", "address": "Carrer de Pau Claris 192, 08037", "phone": "", "hours": "Daily 13:00-01:00", "maps": "https://www.google.com/maps/search/?api=1&query=Bar+Mut+Barcelona" },
  { "id": "v33-boqueria", "cat": "market", "tier": "plenty", "priority": 33, "badge": "MARKET", "name": "Mercat de la Boqueria", "neighborhood": "Las Ramblas · since 1840", "lat": 41.3819, "lng": 2.1718, "tags": ["UNESCO-icon market · go to the perimeter, not the front rows", "Free entry"], "productTags": ["Market"], "why": "Open since 1840, Modernist iron canopy 1914. The famous front rows along Las Ramblas are tourist-bait — go to the back perimeter (fish hall, mushroom stalls, pickled-veg stand) for the working market. Best at 09:00 weekdays.", "address": "La Rambla 91, 08001", "phone": "", "hours": "Mon-Sat 08:00-20:30", "maps": "https://www.google.com/maps/search/?api=1&query=Mercat+de+la+Boqueria" },
  { "id": "v34-sant-antoni", "cat": "market", "tier": "plenty", "priority": 34, "badge": "MARKET", "name": "Mercat de Sant Antoni", "neighborhood": "Sant Antoni · 1882, restored 2018", "lat": 41.3793, "lng": 2.1632, "tags": ["1882 iron-and-glass market · Sunday book + coin market", "Free entry"], "productTags": ["Market"], "why": "1882 iron-and-glass market hall, restored 2018 (revealing 4th-c. Roman walls in the basement). The serious local food market. Sunday morning the surrounding streets host Barcelona's book-and-coin market — a 100-year tradition.", "address": "Carrer Comte d'Urgell 1, 08011", "phone": "", "hours": "Mon-Thu 08:00-20:30, Fri-Sat 08:00-22:00, Sun 08:30-15:00", "maps": "https://www.google.com/maps/search/?api=1&query=Mercat+de+Sant+Antoni" },
  { "id": "p-bougie-casa-fuster", "cat": "bougie", "tier": "plenty", "priority": 90, "badge": "PRESTIGE", "name": "Hotel Casa Fuster", "neighborhood": "Passeig de Gràcia 132 · Modernist", "lat": 41.3989, "lng": 2.1572, "tags": ["5★ Modernist hotel · Domènech i Montaner 1908 · Aleia 1★", "EUR 350-700/night"], "productTags": [], "why": "Lluís Domènech i Montaner's 1908 Modernist palace, converted to a 5★ hotel. Top of Passeig de Gràcia, rooftop bar with Sagrada-Família view, Aleia (1★ Michelin) on the ground floor. The Modernist sleep address.", "address": "Passeig de Gràcia 132, 08008", "phone": "", "hours": "Hotel", "maps": "https://www.google.com/maps/search/?api=1&query=Hotel+Casa+Fuster+Barcelona" },
  { "id": "p-bougie-mandarin", "cat": "bougie", "tier": "plenty", "priority": 91, "badge": "PRESTIGE", "name": "Mandarin Oriental Barcelona", "neighborhood": "Passeig de Gràcia 38-40", "lat": 41.3956, "lng": 2.1631, "tags": ["5★ on Passeig de Gràcia · Moments 2★ on the ground floor · Banker's Bar", "EUR 600-1500/night"], "productTags": [], "why": "5★ on Passeig de Gràcia. Moments (2★, Carme Ruscalleda) is the house restaurant; the Banker's Bar is the discreet city-cocktail address. Patricia Urquiola interiors. Spa, rooftop pool, the discreet luxury reference.", "address": "Passeig de Gràcia 38-40, 08007", "phone": "", "hours": "Hotel", "maps": "https://www.google.com/maps/search/?api=1&query=Mandarin+Oriental+Barcelona" },
  { "id": "p-bougie-el-palace", "cat": "bougie", "tier": "plenty", "priority": 92, "badge": "PRESTIGE", "name": "El Palace Barcelona", "neighborhood": "Eixample · Gran Via 668", "lat": 41.3911, "lng": 2.1716, "tags": ["1919 classical luxury · the original Ritz of Barcelona", "EUR 500-1200/night"], "productTags": [], "why": "Open 1919 as the Ritz Barcelona — Salvador Dalí lived in the suite for 30 years. Classical Belle Époque interior, marble bathrooms, the room over Gran Via with the fanlight balcony. Rooftop pool. The classical-luxury answer to Casa Fuster's Modernist.", "address": "Gran Via de les Corts Catalanes 668, 08010", "phone": "", "hours": "Hotel", "maps": "https://www.google.com/maps/search/?api=1&query=El+Palace+Barcelona" }
];
    const NEIGHBORHOODS = [
        { id: 'n-gothic', name: 'Gothic Quarter (Barri Gòtic)', center: [41.3838, 2.1761], radius: 280, maps_url: 'https://www.google.com/maps/search/?api=1&query=Barri+Gotic+Barcelona' },
        { id: 'n-born', name: 'Born / La Ribera', center: [41.3848, 2.1815], radius: 280, maps_url: 'https://www.google.com/maps/search/?api=1&query=El+Born+Barcelona' },
        { id: 'n-raval', name: 'Raval', center: [41.3804, 2.1700], radius: 320, maps_url: 'https://www.google.com/maps/search/?api=1&query=El+Raval+Barcelona' },
        { id: 'n-eixample', name: 'Eixample (Right Side)', center: [41.3939, 2.1622], radius: 600, maps_url: 'https://www.google.com/maps/search/?api=1&query=Eixample+Dreta' },
        { id: 'n-gracia', name: 'Gràcia', center: [41.4036, 2.1561], radius: 380, maps_url: 'https://www.google.com/maps/search/?api=1&query=Gracia+Barcelona' },
        { id: 'n-poble-sec', name: 'Poble Sec', center: [41.3729, 2.1611], radius: 340, maps_url: 'https://www.google.com/maps/search/?api=1&query=Poble+Sec+Barcelona' },
        { id: 'n-sant-antoni', name: 'Sant Antoni', center: [41.3793, 2.1632], radius: 280, maps_url: 'https://www.google.com/maps/search/?api=1&query=Sant+Antoni+Barcelona' },
        { id: 'n-barceloneta', name: 'Barceloneta', center: [41.3795, 2.1900], radius: 320, maps_url: 'https://www.google.com/maps/search/?api=1&query=Barceloneta+Barcelona' },
        { id: 'n-sarria', name: 'Sarrià', center: [41.4041, 2.1283], radius: 380, maps_url: 'https://www.google.com/maps/search/?api=1&query=Sarria+Barcelona' },
        { id: 'n-poblenou', name: 'Poblenou (22@)', center: [41.4036, 2.1985], radius: 500, maps_url: 'https://www.google.com/maps/search/?api=1&query=Poblenou+Barcelona' }
    ];
    const WALKS = [
        { id: 'w-modernist', name: 'Modernist Passeig de Gràcia', start: [41.3917, 2.1649], maps_url: 'https://www.google.com/maps/search/?api=1&query=Casa+Batllo+Passeig+de+Gracia' },
        { id: 'w-vermut-poble-sec', name: "L'hora del vermut crawl (Poble Sec)", start: [41.3729, 2.1611], maps_url: 'https://www.google.com/maps/search/?api=1&query=Poble+Sec+Barcelona+vermut' },
        { id: 'w-born-ribera', name: 'Born + Ribera architectural walk', start: [41.3838, 2.1828], maps_url: 'https://www.google.com/maps/search/?api=1&query=Santa+Maria+del+Mar' },
        { id: 'w-bunkers-sunset', name: 'Bunkers del Carmel sunset hike', start: [41.4181, 2.1593], maps_url: 'https://www.google.com/maps/search/?api=1&query=Bunkers+del+Carmel' },
        { id: 'w-gracia-squares', name: 'Gràcia squares circuit', start: [41.4031, 2.1561], maps_url: 'https://www.google.com/maps/search/?api=1&query=Placa+del+Sol+Gracia' }
    ];
    const LANDMARKS = [
        { id: 'l-sagrada-familia', name: 'Sagrada Família (Gaudí)', coords: [41.4036, 2.1744], maps_url: 'https://www.google.com/maps/search/?api=1&query=Sagrada+Familia' },
        { id: 'l-park-guell', name: 'Park Güell (Gaudí)', coords: [41.4145, 2.1527], maps_url: 'https://www.google.com/maps/search/?api=1&query=Park+Guell' },
        { id: 'l-casa-batllo', name: 'Casa Batlló (Gaudí)', coords: [41.3917, 2.1649], maps_url: 'https://www.google.com/maps/search/?api=1&query=Casa+Batllo' },
        { id: 'l-pedrera', name: 'La Pedrera / Casa Milà (Gaudí)', coords: [41.3954, 2.1620], maps_url: 'https://www.google.com/maps/search/?api=1&query=La+Pedrera+Casa+Mila' },
        { id: 'l-casa-vicens', name: 'Casa Vicens (Gaudí, first house, 1885)', coords: [41.4053, 2.1505], maps_url: 'https://www.google.com/maps/search/?api=1&query=Casa+Vicens' },
        { id: 'l-sant-pau', name: 'Hospital Sant Pau (UNESCO)', coords: [41.4118, 2.1742], maps_url: 'https://www.google.com/maps/search/?api=1&query=Hospital+de+Sant+Pau' },
        { id: 'l-palau-musica', name: 'Palau de la Música (UNESCO)', coords: [41.3873, 2.1755], maps_url: 'https://www.google.com/maps/search/?api=1&query=Palau+de+la+Musica+Catalana' },
        { id: 'l-cathedral', name: 'Cathedral of Barcelona', coords: [41.3839, 2.1764], maps_url: 'https://www.google.com/maps/search/?api=1&query=Catedral+de+Barcelona' },
        { id: 'l-santa-maria-del-mar', name: 'Santa Maria del Mar (Catalan Gothic basilica)', coords: [41.3838, 2.1830], maps_url: 'https://www.google.com/maps/search/?api=1&query=Santa+Maria+del+Mar' },
        { id: 'l-bunkers', name: 'Bunkers del Carmel (1937 anti-aircraft)', coords: [41.4181, 2.1593], maps_url: 'https://www.google.com/maps/search/?api=1&query=Bunkers+del+Carmel' },
        { id: 'l-tibidabo', name: 'Sagrat Cor de Tibidabo (512m, free)', coords: [41.4226, 2.1186], maps_url: 'https://www.google.com/maps/search/?api=1&query=Sagrat+Cor+Tibidabo' },
        { id: 'l-castell-montjuic', name: 'Castell de Montjuïc (1640)', coords: [41.3635, 2.1657], maps_url: 'https://www.google.com/maps/search/?api=1&query=Castell+de+Montjuic' },
        { id: 'l-pavello-mies', name: 'Pavelló Mies van der Rohe (1929)', coords: [41.3706, 2.1500], maps_url: 'https://www.google.com/maps/search/?api=1&query=Pavello+Mies+van+der+Rohe' },
        { id: 'l-mnac', name: 'MNAC (Museu Nacional d\'Art de Catalunya)', coords: [41.3686, 2.1538], maps_url: 'https://www.google.com/maps/search/?api=1&query=MNAC+Barcelona' },
        { id: 'l-picasso', name: 'Museu Picasso', coords: [41.3852, 2.1808], maps_url: 'https://www.google.com/maps/search/?api=1&query=Museu+Picasso+Barcelona' },
        { id: 'l-sant-pau-pintxo', name: 'Sant Pau · Mercat de Sant Antoni', coords: [41.3793, 2.1632], maps_url: 'https://www.google.com/maps/search/?api=1&query=Mercat+de+Sant+Antoni' },
        { id: 'l-santa-caterina', name: 'Mercat de Santa Caterina (Miralles roof)', coords: [41.3858, 2.1779], maps_url: 'https://www.google.com/maps/search/?api=1&query=Mercat+de+Santa+Caterina' }
    ];
    const WORK_SPOTS = [
        { id: 'p-work-bonay-rooftop', name: 'Casa Bonay rooftop', start: [41.3902, 2.1745] },
        { id: 'p-work-petitbo', name: 'Granja Petitbo', start: [41.3940, 2.1727] },
        { id: 'p-work-mercer', name: 'Hotel Mercer (Roman walls)', start: [41.3829, 2.1788] },
        { id: 'p-work-almirall-morning', name: 'Casa Almirall morning vermut', start: [41.3819, 2.1657] },
        { id: 'p-work-petritxol-chocolate', name: 'Carrer Petritxol — granjas row', start: [41.3833, 2.1745] }
    ];
    return { VENUES, COLORS, CAT_LABELS, PRODUCT_COLORS, NEIGHBORHOODS, WALKS, WORK_SPOTS, LANDMARKS };
})();
